version: '3.7'

services:
  postgres:
    image: postgres:12.9
    ports:
      - "5432:5432"
    volumes:
#      - ${BASE_PATH:-.}/docker-compose/db-scripts:/docker-entrypoint-initdb.d/:ro
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123

volumes:
  data: